{
 "title": "Simple Dashboard Challenge",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Nodes Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{container=\"node-exporter\"}) by (container)"
    }
   ]
  },
  {
   "title": "Total Memory Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{container=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{id=\"/\"}) / sum(node_memory_MemTotal_bytes{container=\"node-exporter\"})) * 100",
     "legendFormat": "Mem (%)"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"node-exporter\"}) by (container)"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cluster:node_cpu:sum_rate5m", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "Pod Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}