name: Docker Build

on:
  pull_request:
    branches:
      - master

jobs:
  docker_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.4
    - name: Docker Build
      uses: docker/build-push-action@v2.5.0
      with:
        context: project-files/docker