name: Docker Build

on:
  pull_request:
    branches:
      - master

jobs:
  docker_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.4
    - name: Install Docker
      run: |
        apt update && \
        apt install -y curl && \
        curl -fsSL https://get.docker.com -o get-docker.sh && \
        sh get-docker.sh
    - name: Docker Build
      run: docker build -t pipeline-test .
      working-directory: project-files/docker